trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: OMF_API_DotNet

jobs:
  - job: Tests_ADH
    pool:
      name: 00-OSIManaged-Build
      demands: Agent.OS -equals Linux
    variables:
      - name: Endpoints.0.Selected
        value: true
      - name: Endpoints.1.Selected
        value: false
      - name: Endpoints.2.Selected
        value: false
      - name: Endpoints.0.TenantId
        value: $(TenantId)
      - name: Endpoints.0.NamespaceId
        value: $(NamespaceId)
      - name: Endpoints.0.ClientId
        value: $(ClientId)
      - name: Endpoints.0.ClientSecret
        value: $(ClientSecret)
      - name: Endpoints.0.Resource
        value: $(Resource)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, ClientId, ClientSecret, Resource'

      - task: DotNetCoreCLI@2
        displayName: 'Nuget restore'
        inputs:
          command: restore

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

  - job: Tests_OnPrem
    pool:
      name: 00-OSIManaged-Build
      demands: Agent.OS -equals Windows_NT
    variables:
      - name: Endpoints.0.Selected
        value: false
      - name: Endpoints.1.Selected
        value: false
      - name: Endpoints.2.Selected
        value: true
      - name: Endpoints.2.Resource
        value: $(PIWebAPI)
      - name: Endpoints.2.Username
        value: $(Username)
      - name: Endpoints.2.Password
        value: $(Password)
      - name: Endpoints.2.DataArchiveName
        value: $(DataArchiveName)
      - name: Endpoints.2.VerifySSL
        value: false
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'Username, Password, PIWebAPI, DataArchiveName'

      - task: DotNetCoreCLI@2
        displayName: 'Nuget restore'
        inputs:
          command: restore

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

  - job: Tests_EDS
    pool:
      name: 00-OSIManaged-Test
      demands: sku2 -equals VSBuildTools.v16.11.7plusAndEDS
    variables:
      - name: Endpoints.0.Selected
        value: false
      - name: Endpoints.1.Selected
        value: true
      - name: Endpoints.2.Selected
        value: false
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'

      - task: DotNetCoreCLI@2
        displayName: 'Nuget restore'
        inputs:
          command: restore

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - task: DotNetCoreCLI@2
          displayName: 'Nuget restore'
          inputs:
            command: restore

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: build

        - template: '/miscellaneous/build_templates/binskim.yml@templates'
